eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8011
spring:
  application:
    name: local-grpc-client
grpc:
  client:
    localService:
      address : static://localhost:9987
      negotiation-type: plaintext
#application:
 # config:
  #  students-url: http://localhost:8222/api/v1/students
   # report-url: http://localhost:8222/api/v1/reports

management:
  tracing:
    sampling:
      probability: 1.0
